
server:
#  port: 8761
  port: 18000

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #是否将将自己作为注册服务注册到注册中心
    register-with-eureka: false
    #是否从其他的注册中心同步服务列表
    fetch-registry: false
    service-url:
      #加入安全认证后的url书写方式
      defaultZone: http://test:test@${eureka.instance.hostname}:18000/eureka/
#      #未加入安全认证后的url书写方式
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    # 设置为false关闭保护模式，默认为true
#    enable-self-preservation: false
#    # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒)
#    eviction-interval-timer-in-ms: 30000

#为注册中心加入安全认证，只有是该认证信息的才能注册
#不进行配置，则默认用户名是user，默认密码是一个随机值，会在项目启动时打印出来
spring.security:
  basic:
    enabled: true   # 启用安全认证处理
  user:
    name: test     # 用户名
    password: test # 密码

