server:
  port: 18005

spring:
  application:
    name: service-hello
  zipkin:
    server-ip: 127.0.0.1
#    server-port: 9411
    server-port: 18003
    base-url: http://${spring.zipkin.server-ip}:${spring.zipkin.server-port}/
  #设置采样比例1.0，默认比例0.1
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      #eureka server 加入安全认证后注册url书写方式
      defaultZone: http://test:test@${eureka.client.server-ip}:${eureka.client.server-port}/eureka/
#      #eureka server 未加入安全认证后注册url书写方式
#      defaultZone: http://${eureka.client.server-ip}:${eureka.client.server-port}/eureka/
#    server-port: 8761
    server-port: 18000
    server-ip: 127.0.0.1
  instance:
#    lease-renewal-interval-in-seconds: 10  #设置心跳的时间间隔（默认是30秒）
#    #表示距离上一次发送心跳之后等待下一次发送心跳的间隔时间，如果超过了此间隔时间，则认为该微服务已经宕机了（默认是90秒）
#    lease-expiration-duration-in-seconds: 20
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}  # 在注册中心信息列表时显示的信息
    prefer-ip-address: true     # 访问的路径变为IP地址


feign:
  hystrix:
    #在feign中开启hystrix功能，默认不开启
    enabled: true

#设置在注册中心中显示的具体信息
info:
  app.name: simple-sprinng-cloud
  company.name: www.simple.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$

